name: CKAN 2.11 on Python 3.12

on:
  push:
  schedule:
    - cron: '0 0 * * 2,4'

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable.yml
    with:
      python-version: "3.12"
      ckan-version: "dev-v2.11"
