name: CKAN master on Python 3.8

on:
  push:
  schedule:
    - cron: '0 0 * * 2,4'

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable.yml
    with:
      python-version: "3.8"
      ckan-version: "master"
