name: CKAN master on Python 3.11

on:
  push:
  schedule:
    - cron: '0 0 * * 2,4'

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable.yml
    with:
      python-version: "3.11"
      ckan-version: "master"
