name: CKAN 2.10 on Python 3.10

on:
  push:
  schedule:
    - cron: '0 0 * * 2,4'

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable.yml
    with:
      python-version: "3.10"
      ckan-version: "dev-v2.10"
